# Generated by Django 4.2 on 2023-04-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('surname', models.CharField(max_length=100, verbose_name='surname')),
                ('patronymic', models.CharField(max_length=100, verbose_name='patronymic')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='photo')),
                ('description', models.TextField(verbose_name='description')),
                ('author', models.ManyToManyField(max_length=100, to='books.authors', verbose_name='author')),
                ('genre', models.ManyToManyField(max_length=100, to='books.genres', verbose_name='genre')),
            ],
        ),
    ]
