# Generated by Django 4.2 on 2023-04-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_popularbooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularbooks',
            options={},
        ),
        migrations.RemoveField(
            model_name='popularbooks',
            name='book',
        ),
        migrations.AddField(
            model_name='popularbooks',
            name='popularbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.books'),
            preserve_default=False,
        ),
    ]
