# Generated by Django 4.2 on 2023-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_popularbooks_options_remove_popularbooks_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ispopular',
            field=models.BooleanField(default=0, verbose_name='ispopular'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PopularBooks',
        ),
    ]
